#!/bin/sh
#  loc_ARRScript.pbs
#  
#  Created by Yuriy Alexandrov on 26/02/2018.
#

# #PBS -lselect=1:ncpus=1:mem=8gb:ngpus=1:gpu_type=GTXTITAN
# #PBS -lselect=1:ncpus=1:mem=8gb:ngpus=1:gpu_type=K80
# #PBS -lselect=1:ncpus=1:mem=8gb:ngpus=1:gpu_type=P100

# ## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=02:00:0
# ## ask for 4 jobs with GPU
#PBS -lselect=1:ncpus=1:mem=8gb:ngpus=1
#PBS -J 1-4

$HOME/OPT_Reconstruction/OPT_NodeScript.sh $ARGS

exit
