function addpath_ALYtools()
        
if ~isdeployed
    
        thisdir = fileparts( mfilename( 'fullpath' ) );
        addpath( thisdir,...
                [thisdir filesep 'Classes'],...
                [thisdir filesep 'GeneratedFiles'],...
                [thisdir filesep 'HelperFunctions'],...                
                [thisdir filesep 'InternalHelperFunctions'],...                
                [thisdir filesep 'HelperFunctions' filesep 'xml_io_tools'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout' filesep 'Patch'],...
                [thisdir filesep 'HelperFunctions' filesep 'GUILayout' filesep 'layoutHelp'],...          
                [thisdir filesep 'HelperFunctions' filesep 'xlwrite'],...
                [thisdir filesep 'BFMatlab'],...                                
                [thisdir filesep 'GUIDEInterfaces'],...                                
                [thisdir filesep 'OMEROUtilities'],...                                                
                [thisdir filesep 'OMEuiUtils'],... 
                [thisdir filesep 'ICUtilities'],...
                [thisdir filesep 'TwIST_OPT'],...                
                [thisdir filesep 'SegmentationFunctions'],...
                [thisdir filesep 'SegmentationFunctions' filesep 'Support'],...
                [thisdir filesep 'Diffusion'],...
                [thisdir filesep 'Skeleton3D'],...
                [thisdir filesep 'Skeleton3D' filesep 'Skel2Graph3D'],...
                [thisdir filesep 'SIFNE'],...                
                [matlabroot filesep 'toolbox' filesep 'images' filesep 'images']); 

        if (verLessThan('matlab', '8.4'))
            % using Matlab before v2014b, use old GUILayout
            addpath([thisdir filesep 'HelperFunctions' filesep 'GUILayout-v1p17'], ...
                    [thisdir filesep 'HelperFunctions' filesep 'GUILayout-v1p17' filesep 'Patch']);
        else
            addpath([thisdir filesep 'HelperFunctions' filesep 'GUI Layout Toolbox' filesep 'layout']);
        end

        addpath( ...
                [thisdir filesep 'OMEROMatlab'],... 
                [thisdir filesep 'OMEROMatlab' filesep 'helper'],... 
                [thisdir filesep 'OMEROMatlab' filesep 'io'],... 
                [thisdir filesep 'OMEROMatlab' filesep 'libs'],... 
                [thisdir filesep 'OMEROMatlab' filesep 'roi']);
                           
            addpath( ...
                [thisdir filesep 'icy_matlab' filesep 'matlabcommunicator'],... 
                [thisdir filesep 'icy_matlab' filesep 'matlabxserver']);                                                
end
            
end