
folder = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour'];
ometiffilename = [pwd filesep 'TestData' filesep 'Fish 3 - Tumour.OME.tiff'];

if exist(ometiffilename,'file')
    delete(ometiffilename);
end;

addpath_OMEkit;

labels = (0:1:39); 
Tags_SeparatingSeq = 'jkhsadfgleufyihtiwurehfjkiblaherb';
Tags = ['Raw Fish' Tags_SeparatingSeq 'Fried Fish' Tags_SeparatingSeq 'Gefilte Fish' Tags_SeparatingSeq 'Icy Fish'];

save_OPT_stack_as_OMEtiff_with_metadata(folder, ometiffilename, ...
                    'ModuloZ_Type', 'Rotation', ...
                    'ModuloZ_TypeDescription', 'OPT', ...
                    'ModuloZ_Unit', 'degree', ...
                    'ModuloZ_Start', 0, ...
                    'ModuloZ_Step', 1, ...
                    'ModuloZ_End', 359, ... 
                            'ModuloC_Type', 'wavelength', ...                        
                            'ModuloC_TypeDescription', 'Excitation', ...
                            'ModuloC_Unit', 'nm', ...
                            'ModuloC_Start', 340, ...
                            'ModuloC_Step', 20, ...
                            'ModuloC_End', 620, ...    
                        'ModuloT_Type', 'lifetime', ...
                        'ModuloT_TypeDescription', 'Gated', ...
                        'ModuloT_Unit', 'ps', ...
                        'ModuloT_Start', 0, ...
                        'ModuloT_Step', 1000, ...
                        'ModuloT_End', 8000, ... 
                    'verbose', true, ... 
                    'Tags',Tags, ...
                    'Tags_SeparatingSeq', Tags_SeparatingSeq);     
